const NotionTextColors = [
  "default",
  "blue",
  "blue_background",
  "brown",
  "brown_background",
  "gray",
  "gray_background",
  "green",
  "green_background",
  "orange",
  "orange_background",
  "pink",
  "pink_background",
  "purple",
  "purple_background",
  "red",
  "red_background",
  "yellow",
  "yellow_background",
] as const

export type NotionTextColor = typeof NotionTextColors[number]

export const NotionTextColorsMap = {
  default: "text-notion-default",
  blue: "text-notion-blue",
  blue_background: "bg-notion-blue",
  brown: "text-notion-brown",
  brown_background: "bg-notion-brown",
  gray: "text-notion-gray",
  gray_background: "bg-notion-gray",
  green: "text-notion-green",
  green_background: "bg-notion-green",
  orange: "text-notion-orange",
  orange_background: "bg-notion-orange",
  pink: "text-notion-pink",
  pink_background: "bg-notion-pink",
  purple: "text-notion-purple",
  purple_background: "bg-notion-purple",
  red: "text-notion-red",
  red_background: "bg-notion-red",
  yellow: "text-notion-yellow",
  yellow_background: "bg-notion-yellow",
} satisfies Record<NotionTextColor, string>

